export const MOBILE_BREAKPOINT_PX = 768;
export const SMALL_MOBILE_BREAKPOINT_PX = 480;
export const BOOT_DURATION_MS = 3200;
export const WINDOW_TITLEBAR_HEIGHT_PX = 30;
export const WINDOW_MIN_VISIBLE_TITLEBAR_PX = 160;
export const DESKTOP_CANVAS_COLOR = '#C0C0C0';
